print("Welcome to the Ips 1.0!")
password=input("Enter your password: ")
print("What you want to execute?")
execute=input("")
print("Welcome to the Google Chromium! What do you want to search?")
search=input("")
print("If you want to make a good apple pie, you need good hands and the recipe of a apple pie, then you make a good apple pie.")
idle=input("")
print("What you want to search?")
search=input("")
print("What you want to Execute?")
execute=input("")
print("Shuting Down... Please Press Enter")
enter=input("")